FORMAT: 1A
HOST: http://hardteddy.ru/

# hardteddy
Общая структура ответа сервера:

    {
        status: [0-1],
        body: [...]
    }
    
+ status = 0 - запрос выполнился верно;
+ status = 1 - запрос не выполнился.

## Сохранение запросов [/api/saveapi/*]
Любой Post/Get запрос на /api/saveapi/[RANDOM] будет сохранен в логи.
### Сохранение GET запрос [GET]
+ Response 200 (application/json)

### Сохранение POST запроса [POST]
+ Response 200 (application/json)


##Group Пользователь

## Регистрация [/api/user/register]
Создание пользователя, необходимые поля
+ name - логин пользователя, <br>
    + является уникальным ключем
    + длина от 3 до 16 символов 
    + только символы (латинские) и цифры
+ email - почта пользователя
    + на почту будет выслано письмо [TODO]
+ password1 - пароль,
    + принимается пароль, длина которого >= 6 символов
+ password2 - подтверждение пароля

Ошибки:
+ email:
    + 0 - не прошел валидацию
+ login: 
    + 0 - не прошел валидацию
    + 1 - логин уже существует
+ password: 
    + 0 - не прошел валидацию
    + 1 - не совпадает с проверочным паролем
+ request:
    + 0 - невалидный json


Пример ответа с ошибкой:

    {
        "body": {
            "email": [
                0
                ],
            "login": [
                0
            ],
            "password": [
                0,
                1
            ]
        },
        "status": 1
    }

### Пример запроса [POST]
+ Request (application/json)

        {
            "name": "MyUniqueName", 
            "email": "email@email.com", 
            "password1": "password",
            "password2": "password"
        }
+ Response 200 (application/json)

            {
            "body": {
            "irissessionid": "akNsSFpOeGZtTnZ4anpQaWhOYlVwSm5HdXpyaG56V08="
            },
            "status": 0
        }

## Авторизация [/api/user/login]
Создание пользователя, необходимые поля
+ name - логин 
+ password - пароль

Ошибки:
+ request:
    + 0 - невалидный json
    + 1 - логин/пароль не найде


Пример ответа с ошибкой:

    {
        "body": {
            "request": [
                1
            ]
        },
        "status": 1
    }

### Пример запроса [POST]
+ Request (application/json)

        {
            "name": "MyUniqueName", 
            "password": "password"
        }
+ Response 200 (application/json)

        {
            "body": {
            "irissessionid": "akNsSFpOeGZtTnZ4anpQaWhOYlVwSm5HdXpyaG56V08="
            },
            "status": 0
        }
        
## Выход [/api/user/logout]
Сервер удаляет сессию клиента

### Пример запроса [POST]
+ Request (application/json)

+ Response 200 (application/json)

        {
            "body": {
            },
            "status": 0
        }

## Категории сказок [/api/store/category/getall]
Получить все категории сказок

### Пример запроса [GET]
+ Request (application/json)

+ Response 200 (application/json)

        {
            "body": {
                "categories":[
                    {
                        "name":"Категория1",
                        "id":1 
                    },
                    {
                        "name":"Категория2",
                        "id":2
                    }
                ]
            },
            "status": 0
        }

## Магазин [/api/store/story/cat={cat}&page={page}&order={order}]
Получить все категории сказок
cat - [OPTIONAL] default - ALL
page - [OPTIONAL] default - 0
order - [OPTIONAL] default - name

order types:
- name
- duration
- price
### Пример запроса [GET]
+ Request (application/json)

+ Response 200 (application/json)

        {
            "body": {
                "stories":[
                    {
                        "name": "Story1",
                        "description": "Story1 awesome description",
                        "author": "iHelos",
                        "id": 1,
                        "minutes":"46",
                        "seconds":"24",
                        "price": 15
                    },
                    {
                        "name": "Story2",
                        "description": "Story2 awesome description",
                        "author": "AnnJelly",
                        "id": 2,
                        "minutes":"72",
                        "seconds":"11",
                        "price": 25
                    }
                ]
            },
            "status": 0
        }